spring.application.name=khieu

# Spring Datasource
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Config JWT
jwt.base64-secret=${JWT_BASE64_SECRET}
# 1day = 24h * 60m * 60s = 86400s
access-token-validity-in-seconds=${ACCESS_TOKEN_VALIDITY_IN_SECONDS}

refresh-token-validity-in-seconds=${REFRESH_TOKEN_VALIDITY_IN_SECONDS}

# Verify Email
verify-base-url=${VERIFY_BASE_URL}

# Upload File Path
upload-file.base-url=${FILE_UPLOAD_DIR}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

# Config email
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${EMAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${EMAIL_SMTP_STARTTLS_ENABLE}